version: '3.9'

services:
  payroll:
    build:
      context: ./payroll
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./payroll:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@payroll-db:5432/payroll_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@payroll-db:5432/payroll_test
    depends_on:
      - payroll-db

  payroll-db:
    build:
      context: ./payroll/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
