# pull official base image
FROM python:3.8.11-slim-buster

# create the app user
RUN addgroup --system app && adduser --system --group app

# create directory for the app user
RUN mkdir -p /home/app

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/payroll/
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

# install system dependencies
RUN apt-get update \
    && apt-get -y install netcat gcc \
    && apt-get -y install libmagic1 \
    && apt-get clean

# install python dependencies

# install pipenv
RUN pip install --upgrade pip
RUN pip install pipenv

# Copy pipenv files
COPY Pipfile Pipfile.lock ${APP_HOME}

# sync dependencies
RUN pipenv sync --system --pre 

# add app
COPY . .

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app

# run gunicorn
CMD gunicorn --bind 0.0.0.0:$PORT --workers 4 app.main:app -k uvicorn.workers.UvicornWorker